### ISSUE TITLE
Advices

### ISSUE THREAD

**Issue by jvitor83** [jvitor83/angular-seed-hybrid#3]
Hellow @mgechev and @NathanWalker, i have created this repo to try use cordova with the seed.

I know that @NathanWalker wanted something like this on his seed, and initially i was to make a PR, but i think it will conflict with the already proposed there "the same multiplatforms (windows, ios, android, linux, osx and web of course)" and maybe give more complexity.

@mgechev, i have to make some changes at the gulp tasks (almost all) to change the package 'gulp' to `vinyl-fs`, because it allow me to use Symbolic Link (got that idea from the advanced-seed) and added some arguments to the dev_dest and prod_dest at seed.config. Got to ask, would you merge those at the original seed? (Not the cordova itself, only the gulp and seed.config changes). With symbolic link we enable use the same files from the `web` at the `cordova` and vice-versa.

Beside those questions, i would ask you guys to avaliate this project and see if have worthed the work!
Anyway, any advice is welcome!

**Comment by NathanWalker** [comment]
@jvitor83 This is very exciting work, nice job.
I want to dig into this more when I have time. On the surface I might suggest integrating with Ionic v2 since it uses cordova. That would make for a pretty exciting integration I believe. Although it's also nice to have just cordova (I could see both being alternate seed paths).

For the advanced seed, the reason I wouldn't want to merge something like this to master is just simply more to maintain. The stack there already is a bit to maintain. But a separate seed like you have here is a great way forward. Will look more when I can and look fwd to chatting more about it in near future. 👍

**Comment by jvitor83** [comment]
Thanks for the feedback @NathanWalker.
In a near future i will take a look at Ionic2 integration (and how to apply to this seed).
Initially i don't think in let ionic2 out-of-box (because people could use others libs to the project, and that is the beauty of cordova), but maybe in some section at the readme.md or wiki to how to incorporate that. _But maybe a branch could be a way to go too._
Any way, thanks and looking forward for you to try this seed!
